package problems;

import utils.Utils;

public class Problem2 {

    /*
    Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
     */

    public static void solve(){
        evenFibonacciNumbers();
    }

    public static void evenFibonacciNumbers(){
        int result = 0;
        int previous = 1;
        int current = 1;
        while(current < 4000000) {
            current = current + previous;
            previous = current - previous;
            if (Utils.isEven(current)) {
                result += current;
            }
        }
        System.out.println(result);
    }

}
